CC := gcc
CFLAGS := -g -O0 -Wall -Wextra

.PHONY: all
all: 01-pthread 02-pthread 03-pthread \
	 04-pthread 05-pthread 06-pthread \
	 07-pthread 08-pthread 09-pthread \
	 10-pthread 11-pthread 12-pthread \
	 13-pthread 14-pthread 15-pthread \
	 16-pthread 17-pthread 18-pthread

.PHONY: 01-pthread
01-pthread: 01-pthread.c
	@echo "Compiling $@"
	@$(CC) $(CFLAGS) -o $@ $^ -lpthread

.PHONY: 02-pthread
02-pthread: 02-pthread.c
	@echo "Compiling $@"
	@$(CC) $(CFLAGS) -o $@ $^ -lpthread

.PHONY: 03-pthread
03-pthread: 03-pthread.c
	@echo "Compiling $@"
	@$(CC) $(CFLAGS) -o $@ $^ -lpthread

.PHONY: 04-pthread
04-pthread: 04-pthread.c
	@echo "Compiling $@"
	@$(CC) $(CFLAGS) -o $@ $^ -lpthread

.PHONY: 05-pthread
05-pthread: 05-pthread.c
	@echo "Compiling $@"
	@$(CC) $(CFLAGS) -o $@ $^ -lpthread

.PHONY: 06-pthread
06-pthread: 06-pthread.c
	@echo "Compiling $@"
	@$(CC) $(CFLAGS) -o $@ $^ -lpthread

.PHONY: 07-pthread
07-pthread: 07-pthread.c
	@echo "Compiling $@"
	@$(CC) $(CFLAGS) -o $@ $^ -lpthread

.PHONY: 08-pthread
08-pthread: 08-pthread.c
	@echo "Compiling $@"
	@$(CC) $(CFLAGS) -o $@ $^ -lpthread

.PHONY: 09-pthread
09-pthread: 09-pthread.c
	@echo "Compiling $@"
	@$(CC) $(CFLAGS) -o $@ $^ -lpthread

.PHONY: 10-pthread
10-pthread: 10-pthread.c
	@echo "Compiling $@"
	@$(CC) $(CFLAGS) -o $@ $^ -lpthread

.PHONY: 11-pthread
11-pthread: 11-pthread.c
	@echo "Compiling $@"
	@$(CC) $(CFLAGS) -o $@ $^ -lpthread

.PHONY: 12-pthread
12-pthread: 12-pthread.c
	@echo "Compiling $@"
	@$(CC) $(CFLAGS) -o $@ $^ -lpthread

.PHONY: 13-pthread
13-pthread: 13-pthread.c
	@echo "Compiling $@"
	@$(CC) $(CFLAGS) -o $@ $^ -lpthread

.PHONY: 14-pthread
14-pthread: 14-pthread.c
	@echo "Compiling $@"
	@$(CC) $(CFLAGS) -o $@ $^ -lpthread

.PHONY: 15-pthread
15-pthread: 15-pthread.c
	@echo "Compiling $@"
	@$(CC) $(CFLAGS) -o $@ $^ -lpthread

.PHONY: 16-pthread
16-pthread: 16-pthread.c
	@echo "Compiling $@"
	@$(CC) $(CFLAGS) -o $@ $^ -lpthread

.PHONY: 17-pthread
17-pthread: 17-pthread.c
	@echo "Compiling $@"
	@$(CC) $(CFLAGS) -o $@ $^ -lpthread

.PHONY: 18-pthread
18-pthread: 18-pthread.c
	@echo "Compiling $@"
	@$(CC) $(CFLAGS) -o $@ $^ -lpthread

.PHONY: clean
clean:
	@echo "Remove obj files..."
	@rm -f *.o *.a \
		01-pthread 02-pthread 03-pthread \
		04-pthread 05-pthread 06-pthread \
		07-pthread 08-pthread 09-pthread \
		10-pthread 11-pthread 12-pthread \
		13-pthread 14-pthread 15-pthread \
		16-pthread 17-pthread 18-pthread